apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes-rest-backend
        image: alexandar99naydenov/notes_rest_application
        ports:
        - containerPort: 12345
        volumeMounts:
            - mountPath: /app/data
              name: notes-volume
      volumes:
      - name: notes-volume
        persistentVolumeClaim:
          claimName: notes-pvc
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
spec:
  type: NodePort
  selector:
    app: notes
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345