name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
      - name: Jacoco Test Coverage
        uses: madrapps/jacoco-report@v1.1
        with:
          path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml     
          token: ${{ secrets.ACCESS_TOKEN }}
